<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Project 3</title>
    <?php $thisPage="home" ?>
    <?php include "inc/top.inc"; ?>
    <?php include "inc/nav.inc"; ?>


    <!-- Top Section -->
    <section id="first">
        <div class="container">
        <h1>Annie Zhang</h1>
        <p>A senior at the University of Rochester and a computer science major. Scroll down to read about them or <a href="#second"> click here to read about accomplishments!</a></p>
        <img src="images/annie.jpg" alt="Annie Zhang">
       </div><!-- .container -->

    </section>

    <!-- Second Section -->
    <section id="second">
      <div class="container accomplish">
        <h1>Accomplishments</h1>
        <table>
          <tr><img src="images/flower.jpg" alt="Flower" class="second-pic"></tr>
          <tr><p>Lab 1 of CSC 174. This lab was an account setup and used to refamiliarize the class with the basics of HTML and CSS that we learned in CSC 170. You can see my Lab 1 <a href="http://urcsc170.org/azhang/lab01/">here</a>. This lab was pretty basic and included lorem ipsum text. This lab was also the lab where I learned about W3C's move to include lang as an attribute for html and their giving it a warning is in an attempt to move toward having it be an error in the future.</p></tr>
          <tr><img src="images/pets.jpg" alt="Pet" class="second-pic"></tr>
          <tr><p>Lab 2 of CSC 174. This lab was to explore PHP includes. You can see my lab 2 <a href="http://urcsc170.org/azhang/lab02/index.php">here.</a> This content was generated by Professor Kotin and I only moved information around with the PHP includes.</p></tr>
        </table>
      
     </div><!-- .container -->

    </section>

</body>

</html>
