<!-- Navigation -->
    <nav class="main-menu">
        <ul>
            <li <?php if($thisPage=="home") { echo 'class="active"'; } ?>>><a href="index.html#first">About</a></li>
            <li <?php if($thisPage=="home2") { echo 'class="active"'; } ?>>><a href="index.html#second">Accomplishment</a></li>
            <li <?php if($thisPage=="portfolio") { echo 'class="active"'; } ?>>><a href="portfolio">Portfolio</a></li>
            <li <?php if($thisPage=="contact") { echo 'class="active"'; } ?>>><a href="contact.php"></a></li>
        </ul>
    </nav>